
      with:
        fetch-depth: 2
    - uses: docker://whatwg/html-deploy:latest
      env:
        HTML_SOURCE: /github/workspace # FIXME
        SERVER: ${{ secrets.MARQUEE_SERVER }}
        SERVER_PUBLIC_KEY: ${{ secrets.MARQUEE_PUBLIC_KEY }}
        SERVER_DEPLOY_KEY: ${{ secrets.MARQUEE_DEPLOY_KEY }}
